baseURL: http://example.org/
languageCode: en-us
title: Portfolio Website for Zervaan Borok
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Welcome to my personal website. 
      Here I share some of the R and Python work that I do.
    title: Hi, my name is Zervaan Borok 
  blog: {}
  contact:
    address:
      - city: London 
        country: United Kingdom
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: zborok.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 07833 667439
        title: Phone
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Zervaan Borok, 2021, GitHub, the R Blogdown package, and the Forty theme from Hugo
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/zborok
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/zervaan-borok-535b27195
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Undergraduate Dissertation
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
