baseURL: https://zervaan-borok.netlify.app/
languageCode: en-us
title: Portfolio Website for Zervaan Borok
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Welcome to my personal website. 
      Here I share some of the R and Python work that I do.
    title: Hi, my name is Zervaan Borok 
  blog: {}
  contact:
    address:
      - city: London 
        country: United Kingdom
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email: 
      - email: zborok.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +1 630 750 6026
        title: Phone
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Zervaan Borok, 2021, GitHub, the R Blogdown package, and the Forty theme from Hugo
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/zborok
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/zervaan-borok-535b27195
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
   # subtitle: By HTML5 Up
    title: Borok
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: An Attempt to Model Horse Races
        title: Undergraduate Dissertation
        url: https://github.com/zborok/Dissertation-Code
      - image: pic02.jpg
        subtitle: An Investigation of Worldwide Alcohol Consumption and IMDB Critiqued Movies
        title: Movies and Consumption
        url: https://github.com/zborok/applied_stats_LBS/blob/master/Homework_1.Rmd
      - image: pic03.jpg
        subtitle: An Analysis of the General Social Survey, Climate Change, and Biden's Approval Rate 
        title: Climate Change, Social Survey, and Biden
        url: https://github.com/zborok/applied_stats_LBS/blob/master/Homework_2.Rmd
      - image: pic04.jpg
        subtitle: An Analysis of a Range of Current Affairs
        title: Pay Discrimination, Brexit, and COVID
        url: https://github.com/zborok/applied_stats_LBS/blob/master/homework_3.Rmd
      - image: pic05.jpg
        subtitle: A Mapping of Restaurants in London 
        title: Capstone Project
        url: https://github.com/zborok/Coursera_Capstone/tree/master
    #  - image: pic06.jpg
    #    subtitle: Feugiat Amet Tempus
    #    title: Etiam
    #    url: blogs/ipsum
  two:
 #   buttonText: Get Started
  #  enable: yes
  #  subtitle: 
    title: The Future Is Data
    url: blogs
